#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_de_venta.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PuntoDeVenta")]
	public partial class MyDataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCajero(Cajero instance);
    partial void UpdateCajero(Cajero instance);
    partial void DeleteCajero(Cajero instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertCompras(Compras instance);
    partial void UpdateCompras(Compras instance);
    partial void DeleteCompras(Compras instance);
    partial void Insertdetalle_pago_transaccion(detalle_pago_transaccion instance);
    partial void Updatedetalle_pago_transaccion(detalle_pago_transaccion instance);
    partial void Deletedetalle_pago_transaccion(detalle_pago_transaccion instance);
    partial void Insertdetalle_transaccion(detalle_transaccion instance);
    partial void Updatedetalle_transaccion(detalle_transaccion instance);
    partial void Deletedetalle_transaccion(detalle_transaccion instance);
    partial void InsertDetalle_Ventas(Detalle_Ventas instance);
    partial void UpdateDetalle_Ventas(Detalle_Ventas instance);
    partial void DeleteDetalle_Ventas(Detalle_Ventas instance);
    partial void InsertMetodo_pago(Metodo_pago instance);
    partial void UpdateMetodo_pago(Metodo_pago instance);
    partial void DeleteMetodo_pago(Metodo_pago instance);
    partial void InsertProductos(Productos instance);
    partial void UpdateProductos(Productos instance);
    partial void DeleteProductos(Productos instance);
    partial void InsertProveedor(Proveedor instance);
    partial void UpdateProveedor(Proveedor instance);
    partial void DeleteProveedor(Proveedor instance);
    partial void InsertTransaccion(Transaccion instance);
    partial void UpdateTransaccion(Transaccion instance);
    partial void DeleteTransaccion(Transaccion instance);
    partial void InsertVentas(Ventas instance);
    partial void UpdateVentas(Ventas instance);
    partial void DeleteVentas(Ventas instance);
    #endregion
		
		public MyDataBaseDataContext() : 
				base(global::Punto_de_venta.Properties.Settings.Default.PuntoDeVentaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cajero> Cajero
		{
			get
			{
				return this.GetTable<Cajero>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Compras> Compras
		{
			get
			{
				return this.GetTable<Compras>();
			}
		}
		
		public System.Data.Linq.Table<detalle_pago_transaccion> detalle_pago_transaccion
		{
			get
			{
				return this.GetTable<detalle_pago_transaccion>();
			}
		}
		
		public System.Data.Linq.Table<detalle_transaccion> detalle_transaccion
		{
			get
			{
				return this.GetTable<detalle_transaccion>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_Ventas> Detalle_Ventas
		{
			get
			{
				return this.GetTable<Detalle_Ventas>();
			}
		}
		
		public System.Data.Linq.Table<Metodo_pago> Metodo_pago
		{
			get
			{
				return this.GetTable<Metodo_pago>();
			}
		}
		
		public System.Data.Linq.Table<Productos> Productos
		{
			get
			{
				return this.GetTable<Productos>();
			}
		}
		
		public System.Data.Linq.Table<Proveedor> Proveedor
		{
			get
			{
				return this.GetTable<Proveedor>();
			}
		}
		
		public System.Data.Linq.Table<Transaccion> Transaccion
		{
			get
			{
				return this.GetTable<Transaccion>();
			}
		}
		
		public System.Data.Linq.Table<Ventas> Ventas
		{
			get
			{
				return this.GetTable<Ventas>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cajero")]
	public partial class Cajero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cajero;
		
		private string _usuario;
		
		private string _pass;
		
		private string _nombre;
		
		private string _direccion;
		
		private string _telefono;
		
		private string _correo;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<Transaccion> _Transaccion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_cajeroChanging(int value);
    partial void Onid_cajeroChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public Cajero()
		{
			this._Transaccion = new EntitySet<Transaccion>(new Action<Transaccion>(this.attach_Transaccion), new Action<Transaccion>(this.detach_Transaccion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cajero", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cajero
		{
			get
			{
				return this._id_cajero;
			}
			set
			{
				if ((this._id_cajero != value))
				{
					this.Onid_cajeroChanging(value);
					this.SendPropertyChanging();
					this._id_cajero = value;
					this.SendPropertyChanged("id_cajero");
					this.Onid_cajeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(100)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="Char(100)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(300)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(100)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(100)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cajero_Transaccion", Storage="_Transaccion", ThisKey="id_cajero", OtherKey="id_cajero")]
		public EntitySet<Transaccion> Transaccion
		{
			get
			{
				return this._Transaccion;
			}
			set
			{
				this._Transaccion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transaccion(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Cajero = this;
		}
		
		private void detach_Transaccion(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Cajero = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_cliente;
		
		private string _nombres;
		
		private string _apellidos;
		
		private string _direccion;
		
		private string _telefono;
		
		private string _correo;
		
		private int _cantidad;
		
		private bool _estado;
		
		private EntitySet<Transaccion> _Transaccion;
		
		private EntitySet<Ventas> _Ventas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_clienteChanging(int value);
    partial void OnId_clienteChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    #endregion
		
		public Cliente()
		{
			this._Transaccion = new EntitySet<Transaccion>(new Action<Transaccion>(this.attach_Transaccion), new Action<Transaccion>(this.detach_Transaccion));
			this._Ventas = new EntitySet<Ventas>(new Action<Ventas>(this.attach_Ventas), new Action<Ventas>(this.detach_Ventas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_cliente
		{
			get
			{
				return this._Id_cliente;
			}
			set
			{
				if ((this._Id_cliente != value))
				{
					this.OnId_clienteChanging(value);
					this.SendPropertyChanging();
					this._Id_cliente = value;
					this.SendPropertyChanged("Id_cliente");
					this.OnId_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string apellidos
		{
			get
			{
				return this._apellidos;
			}
			set
			{
				if ((this._apellidos != value))
				{
					this.OnapellidosChanging(value);
					this.SendPropertyChanging();
					this._apellidos = value;
					this.SendPropertyChanged("apellidos");
					this.OnapellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(100)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Transaccion", Storage="_Transaccion", ThisKey="Id_cliente", OtherKey="Id_cliente")]
		public EntitySet<Transaccion> Transaccion
		{
			get
			{
				return this._Transaccion;
			}
			set
			{
				this._Transaccion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Ventas", Storage="_Ventas", ThisKey="Id_cliente", OtherKey="Id_cliente")]
		public EntitySet<Ventas> Ventas
		{
			get
			{
				return this._Ventas;
			}
			set
			{
				this._Ventas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transaccion(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Transaccion(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_Ventas(Ventas entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Ventas(Ventas entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Compras")]
	public partial class Compras : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_compra;
		
		private System.Nullable<int> _Nit;
		
		private string _nombre;
		
		private System.Nullable<decimal> _precio;
		
		private System.Nullable<decimal> _total;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<Productos> _Productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_compraChanging(int value);
    partial void Onid_compraChanged();
    partial void OnNitChanging(System.Nullable<int> value);
    partial void OnNitChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public Compras()
		{
			this._Productos = new EntitySet<Productos>(new Action<Productos>(this.attach_Productos), new Action<Productos>(this.detach_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_compra", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_compra
		{
			get
			{
				return this._id_compra;
			}
			set
			{
				if ((this._id_compra != value))
				{
					this.Onid_compraChanging(value);
					this.SendPropertyChanging();
					this._id_compra = value;
					this.SendPropertyChanged("id_compra");
					this.Onid_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nit", DbType="Int")]
		public System.Nullable<int> Nit
		{
			get
			{
				return this._Nit;
			}
			set
			{
				if ((this._Nit != value))
				{
					this.OnNitChanging(value);
					this.SendPropertyChanging();
					this._Nit = value;
					this.SendPropertyChanged("Nit");
					this.OnNitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Money")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Money")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Compras_Productos", Storage="_Productos", ThisKey="id_compra", OtherKey="id_compra")]
		public EntitySet<Productos> Productos
		{
			get
			{
				return this._Productos;
			}
			set
			{
				this._Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Productos(Productos entity)
		{
			this.SendPropertyChanging();
			entity.Compras = this;
		}
		
		private void detach_Productos(Productos entity)
		{
			this.SendPropertyChanging();
			entity.Compras = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detalle_pago_transaccion")]
	public partial class detalle_pago_transaccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_detalle_transaccion;
		
		private System.Nullable<decimal> _monto;
		
		private System.Nullable<bool> _estado;
		
		private int _id_transaccion;
		
		private int _id_metodo_pago;
		
		private EntityRef<Metodo_pago> _Metodo_pago;
		
		private EntityRef<Transaccion> _Transaccion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_detalle_transaccionChanging(int value);
    partial void Onid_detalle_transaccionChanged();
    partial void OnmontoChanging(System.Nullable<decimal> value);
    partial void OnmontoChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    partial void Onid_transaccionChanging(int value);
    partial void Onid_transaccionChanged();
    partial void Onid_metodo_pagoChanging(int value);
    partial void Onid_metodo_pagoChanged();
    #endregion
		
		public detalle_pago_transaccion()
		{
			this._Metodo_pago = default(EntityRef<Metodo_pago>);
			this._Transaccion = default(EntityRef<Transaccion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detalle_transaccion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_detalle_transaccion
		{
			get
			{
				return this._id_detalle_transaccion;
			}
			set
			{
				if ((this._id_detalle_transaccion != value))
				{
					this.Onid_detalle_transaccionChanging(value);
					this.SendPropertyChanging();
					this._id_detalle_transaccion = value;
					this.SendPropertyChanged("id_detalle_transaccion");
					this.Onid_detalle_transaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto", DbType="Money")]
		public System.Nullable<decimal> monto
		{
			get
			{
				return this._monto;
			}
			set
			{
				if ((this._monto != value))
				{
					this.OnmontoChanging(value);
					this.SendPropertyChanging();
					this._monto = value;
					this.SendPropertyChanged("monto");
					this.OnmontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_transaccion", DbType="Int NOT NULL")]
		public int id_transaccion
		{
			get
			{
				return this._id_transaccion;
			}
			set
			{
				if ((this._id_transaccion != value))
				{
					if (this._Transaccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_transaccionChanging(value);
					this.SendPropertyChanging();
					this._id_transaccion = value;
					this.SendPropertyChanged("id_transaccion");
					this.Onid_transaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_metodo_pago", DbType="Int NOT NULL")]
		public int id_metodo_pago
		{
			get
			{
				return this._id_metodo_pago;
			}
			set
			{
				if ((this._id_metodo_pago != value))
				{
					if (this._Metodo_pago.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_metodo_pagoChanging(value);
					this.SendPropertyChanging();
					this._id_metodo_pago = value;
					this.SendPropertyChanged("id_metodo_pago");
					this.Onid_metodo_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Metodo_pago_detalle_pago_transaccion", Storage="_Metodo_pago", ThisKey="id_metodo_pago", OtherKey="id_metodo_pago", IsForeignKey=true)]
		public Metodo_pago Metodo_pago
		{
			get
			{
				return this._Metodo_pago.Entity;
			}
			set
			{
				Metodo_pago previousValue = this._Metodo_pago.Entity;
				if (((previousValue != value) 
							|| (this._Metodo_pago.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Metodo_pago.Entity = null;
						previousValue.detalle_pago_transaccion.Remove(this);
					}
					this._Metodo_pago.Entity = value;
					if ((value != null))
					{
						value.detalle_pago_transaccion.Add(this);
						this._id_metodo_pago = value.id_metodo_pago;
					}
					else
					{
						this._id_metodo_pago = default(int);
					}
					this.SendPropertyChanged("Metodo_pago");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaccion_detalle_pago_transaccion", Storage="_Transaccion", ThisKey="id_transaccion", OtherKey="id_transaccion", IsForeignKey=true)]
		public Transaccion Transaccion
		{
			get
			{
				return this._Transaccion.Entity;
			}
			set
			{
				Transaccion previousValue = this._Transaccion.Entity;
				if (((previousValue != value) 
							|| (this._Transaccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Transaccion.Entity = null;
						previousValue.detalle_pago_transaccion.Remove(this);
					}
					this._Transaccion.Entity = value;
					if ((value != null))
					{
						value.detalle_pago_transaccion.Add(this);
						this._id_transaccion = value.id_transaccion;
					}
					else
					{
						this._id_transaccion = default(int);
					}
					this.SendPropertyChanged("Transaccion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detalle_transaccion")]
	public partial class detalle_transaccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_detalle_transacciion;
		
		private System.Nullable<decimal> _precio;
		
		private System.Nullable<int> _cantidad;
		
		private System.Nullable<bool> _estado;
		
		private int _id_transaccion;
		
		private int _id_producto;
		
		private EntityRef<Productos> _Productos;
		
		private EntityRef<Transaccion> _Transaccion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_detalle_transacciionChanging(int value);
    partial void Onid_detalle_transacciionChanged();
    partial void OnprecioChanging(System.Nullable<decimal> value);
    partial void OnprecioChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    partial void Onid_transaccionChanging(int value);
    partial void Onid_transaccionChanged();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    #endregion
		
		public detalle_transaccion()
		{
			this._Productos = default(EntityRef<Productos>);
			this._Transaccion = default(EntityRef<Transaccion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detalle_transacciion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_detalle_transacciion
		{
			get
			{
				return this._id_detalle_transacciion;
			}
			set
			{
				if ((this._id_detalle_transacciion != value))
				{
					this.Onid_detalle_transacciionChanging(value);
					this.SendPropertyChanging();
					this._id_detalle_transacciion = value;
					this.SendPropertyChanged("id_detalle_transacciion");
					this.Onid_detalle_transacciionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="Money")]
		public System.Nullable<decimal> precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this.OnprecioChanging(value);
					this.SendPropertyChanging();
					this._precio = value;
					this.SendPropertyChanged("precio");
					this.OnprecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_transaccion", DbType="Int NOT NULL")]
		public int id_transaccion
		{
			get
			{
				return this._id_transaccion;
			}
			set
			{
				if ((this._id_transaccion != value))
				{
					if (this._Transaccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_transaccionChanging(value);
					this.SendPropertyChanging();
					this._id_transaccion = value;
					this.SendPropertyChanged("id_transaccion");
					this.Onid_transaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", DbType="Int NOT NULL")]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					if (this._Productos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Productos_detalle_transaccion", Storage="_Productos", ThisKey="id_producto", OtherKey="id_producto", IsForeignKey=true)]
		public Productos Productos
		{
			get
			{
				return this._Productos.Entity;
			}
			set
			{
				Productos previousValue = this._Productos.Entity;
				if (((previousValue != value) 
							|| (this._Productos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Productos.Entity = null;
						previousValue.detalle_transaccion.Remove(this);
					}
					this._Productos.Entity = value;
					if ((value != null))
					{
						value.detalle_transaccion.Add(this);
						this._id_producto = value.id_producto;
					}
					else
					{
						this._id_producto = default(int);
					}
					this.SendPropertyChanged("Productos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaccion_detalle_transaccion", Storage="_Transaccion", ThisKey="id_transaccion", OtherKey="id_transaccion", IsForeignKey=true)]
		public Transaccion Transaccion
		{
			get
			{
				return this._Transaccion.Entity;
			}
			set
			{
				Transaccion previousValue = this._Transaccion.Entity;
				if (((previousValue != value) 
							|| (this._Transaccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Transaccion.Entity = null;
						previousValue.detalle_transaccion.Remove(this);
					}
					this._Transaccion.Entity = value;
					if ((value != null))
					{
						value.detalle_transaccion.Add(this);
						this._id_transaccion = value.id_transaccion;
					}
					else
					{
						this._id_transaccion = default(int);
					}
					this.SendPropertyChanged("Transaccion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_Ventas")]
	public partial class Detalle_Ventas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_detalle_ventas;
		
		private System.Nullable<int> _cantidad;
		
		private System.Nullable<decimal> _precio_venta;
		
		private System.Nullable<bool> _estado;
		
		private int _id_ventas;
		
		private EntityRef<Ventas> _Ventas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_detalle_ventasChanging(int value);
    partial void Onid_detalle_ventasChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    partial void Onprecio_ventaChanging(System.Nullable<decimal> value);
    partial void Onprecio_ventaChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    partial void Onid_ventasChanging(int value);
    partial void Onid_ventasChanged();
    #endregion
		
		public Detalle_Ventas()
		{
			this._Ventas = default(EntityRef<Ventas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detalle_ventas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_detalle_ventas
		{
			get
			{
				return this._id_detalle_ventas;
			}
			set
			{
				if ((this._id_detalle_ventas != value))
				{
					this.Onid_detalle_ventasChanging(value);
					this.SendPropertyChanging();
					this._id_detalle_ventas = value;
					this.SendPropertyChanged("id_detalle_ventas");
					this.Onid_detalle_ventasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_venta", DbType="Money")]
		public System.Nullable<decimal> precio_venta
		{
			get
			{
				return this._precio_venta;
			}
			set
			{
				if ((this._precio_venta != value))
				{
					this.Onprecio_ventaChanging(value);
					this.SendPropertyChanging();
					this._precio_venta = value;
					this.SendPropertyChanged("precio_venta");
					this.Onprecio_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ventas", DbType="Int NOT NULL")]
		public int id_ventas
		{
			get
			{
				return this._id_ventas;
			}
			set
			{
				if ((this._id_ventas != value))
				{
					if (this._Ventas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ventasChanging(value);
					this.SendPropertyChanging();
					this._id_ventas = value;
					this.SendPropertyChanged("id_ventas");
					this.Onid_ventasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ventas_Detalle_Ventas", Storage="_Ventas", ThisKey="id_ventas", OtherKey="id_ventas", IsForeignKey=true)]
		public Ventas Ventas
		{
			get
			{
				return this._Ventas.Entity;
			}
			set
			{
				Ventas previousValue = this._Ventas.Entity;
				if (((previousValue != value) 
							|| (this._Ventas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ventas.Entity = null;
						previousValue.Detalle_Ventas.Remove(this);
					}
					this._Ventas.Entity = value;
					if ((value != null))
					{
						value.Detalle_Ventas.Add(this);
						this._id_ventas = value.id_ventas;
					}
					else
					{
						this._id_ventas = default(int);
					}
					this.SendPropertyChanged("Ventas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Metodo_pago")]
	public partial class Metodo_pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_metodo_pago;
		
		private string _nombre;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<detalle_pago_transaccion> _detalle_pago_transaccion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_metodo_pagoChanging(int value);
    partial void Onid_metodo_pagoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public Metodo_pago()
		{
			this._detalle_pago_transaccion = new EntitySet<detalle_pago_transaccion>(new Action<detalle_pago_transaccion>(this.attach_detalle_pago_transaccion), new Action<detalle_pago_transaccion>(this.detach_detalle_pago_transaccion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_metodo_pago", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_metodo_pago
		{
			get
			{
				return this._id_metodo_pago;
			}
			set
			{
				if ((this._id_metodo_pago != value))
				{
					this.Onid_metodo_pagoChanging(value);
					this.SendPropertyChanging();
					this._id_metodo_pago = value;
					this.SendPropertyChanged("id_metodo_pago");
					this.Onid_metodo_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Metodo_pago_detalle_pago_transaccion", Storage="_detalle_pago_transaccion", ThisKey="id_metodo_pago", OtherKey="id_metodo_pago")]
		public EntitySet<detalle_pago_transaccion> detalle_pago_transaccion
		{
			get
			{
				return this._detalle_pago_transaccion;
			}
			set
			{
				this._detalle_pago_transaccion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_pago_transaccion(detalle_pago_transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Metodo_pago = this;
		}
		
		private void detach_detalle_pago_transaccion(detalle_pago_transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Metodo_pago = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Productos")]
	public partial class Productos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_producto;
		
		private string _nombre;
		
		private string _descripcion;
		
		private System.Nullable<decimal> _precio_costo;
		
		private System.Nullable<decimal> _precio_venta;
		
		private System.Nullable<int> _cantidad;
		
		private System.Nullable<bool> _estado;
		
		private int _Id_proveedor;
		
		private int _id_compra;
		
		private EntitySet<detalle_transaccion> _detalle_transaccion;
		
		private EntityRef<Compras> _Compras;
		
		private EntityRef<Proveedor> _Proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_productoChanging(int value);
    partial void Onid_productoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onprecio_costoChanging(System.Nullable<decimal> value);
    partial void Onprecio_costoChanged();
    partial void Onprecio_ventaChanging(System.Nullable<decimal> value);
    partial void Onprecio_ventaChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    partial void OnId_proveedorChanging(int value);
    partial void OnId_proveedorChanged();
    partial void Onid_compraChanging(int value);
    partial void Onid_compraChanged();
    #endregion
		
		public Productos()
		{
			this._detalle_transaccion = new EntitySet<detalle_transaccion>(new Action<detalle_transaccion>(this.attach_detalle_transaccion), new Action<detalle_transaccion>(this.detach_detalle_transaccion));
			this._Compras = default(EntityRef<Compras>);
			this._Proveedor = default(EntityRef<Proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_producto
		{
			get
			{
				return this._id_producto;
			}
			set
			{
				if ((this._id_producto != value))
				{
					this.Onid_productoChanging(value);
					this.SendPropertyChanging();
					this._id_producto = value;
					this.SendPropertyChanged("id_producto");
					this.Onid_productoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(100)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_costo", DbType="Money")]
		public System.Nullable<decimal> precio_costo
		{
			get
			{
				return this._precio_costo;
			}
			set
			{
				if ((this._precio_costo != value))
				{
					this.Onprecio_costoChanging(value);
					this.SendPropertyChanging();
					this._precio_costo = value;
					this.SendPropertyChanged("precio_costo");
					this.Onprecio_costoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_venta", DbType="Money")]
		public System.Nullable<decimal> precio_venta
		{
			get
			{
				return this._precio_venta;
			}
			set
			{
				if ((this._precio_venta != value))
				{
					this.Onprecio_ventaChanging(value);
					this.SendPropertyChanging();
					this._precio_venta = value;
					this.SendPropertyChanged("precio_venta");
					this.Onprecio_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_proveedor", DbType="Int NOT NULL")]
		public int Id_proveedor
		{
			get
			{
				return this._Id_proveedor;
			}
			set
			{
				if ((this._Id_proveedor != value))
				{
					if (this._Proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_proveedorChanging(value);
					this.SendPropertyChanging();
					this._Id_proveedor = value;
					this.SendPropertyChanged("Id_proveedor");
					this.OnId_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_compra", DbType="Int NOT NULL")]
		public int id_compra
		{
			get
			{
				return this._id_compra;
			}
			set
			{
				if ((this._id_compra != value))
				{
					if (this._Compras.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_compraChanging(value);
					this.SendPropertyChanging();
					this._id_compra = value;
					this.SendPropertyChanged("id_compra");
					this.Onid_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Productos_detalle_transaccion", Storage="_detalle_transaccion", ThisKey="id_producto", OtherKey="id_producto")]
		public EntitySet<detalle_transaccion> detalle_transaccion
		{
			get
			{
				return this._detalle_transaccion;
			}
			set
			{
				this._detalle_transaccion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Compras_Productos", Storage="_Compras", ThisKey="id_compra", OtherKey="id_compra", IsForeignKey=true)]
		public Compras Compras
		{
			get
			{
				return this._Compras.Entity;
			}
			set
			{
				Compras previousValue = this._Compras.Entity;
				if (((previousValue != value) 
							|| (this._Compras.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Compras.Entity = null;
						previousValue.Productos.Remove(this);
					}
					this._Compras.Entity = value;
					if ((value != null))
					{
						value.Productos.Add(this);
						this._id_compra = value.id_compra;
					}
					else
					{
						this._id_compra = default(int);
					}
					this.SendPropertyChanged("Compras");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedor_Productos", Storage="_Proveedor", ThisKey="Id_proveedor", OtherKey="Id_proveedor", IsForeignKey=true)]
		public Proveedor Proveedor
		{
			get
			{
				return this._Proveedor.Entity;
			}
			set
			{
				Proveedor previousValue = this._Proveedor.Entity;
				if (((previousValue != value) 
							|| (this._Proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proveedor.Entity = null;
						previousValue.Productos.Remove(this);
					}
					this._Proveedor.Entity = value;
					if ((value != null))
					{
						value.Productos.Add(this);
						this._Id_proveedor = value.Id_proveedor;
					}
					else
					{
						this._Id_proveedor = default(int);
					}
					this.SendPropertyChanged("Proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_transaccion(detalle_transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Productos = this;
		}
		
		private void detach_detalle_transaccion(detalle_transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Productos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proveedor")]
	public partial class Proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_proveedor;
		
		private string _nombre_compania;
		
		private string _direccion;
		
		private string _telefono;
		
		private string _correo;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<Productos> _Productos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_proveedorChanging(int value);
    partial void OnId_proveedorChanged();
    partial void Onnombre_companiaChanging(string value);
    partial void Onnombre_companiaChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public Proveedor()
		{
			this._Productos = new EntitySet<Productos>(new Action<Productos>(this.attach_Productos), new Action<Productos>(this.detach_Productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_proveedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_proveedor
		{
			get
			{
				return this._Id_proveedor;
			}
			set
			{
				if ((this._Id_proveedor != value))
				{
					this.OnId_proveedorChanging(value);
					this.SendPropertyChanging();
					this._Id_proveedor = value;
					this.SendPropertyChanged("Id_proveedor");
					this.OnId_proveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_compania", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_compania
		{
			get
			{
				return this._nombre_compania;
			}
			set
			{
				if ((this._nombre_compania != value))
				{
					this.Onnombre_companiaChanging(value);
					this.SendPropertyChanging();
					this._nombre_compania = value;
					this.SendPropertyChanged("nombre_compania");
					this.Onnombre_companiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(100)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedor_Productos", Storage="_Productos", ThisKey="Id_proveedor", OtherKey="Id_proveedor")]
		public EntitySet<Productos> Productos
		{
			get
			{
				return this._Productos;
			}
			set
			{
				this._Productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Productos(Productos entity)
		{
			this.SendPropertyChanging();
			entity.Proveedor = this;
		}
		
		private void detach_Productos(Productos entity)
		{
			this.SendPropertyChanging();
			entity.Proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transaccion")]
	public partial class Transaccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_transaccion;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<decimal> _total;
		
		private System.Nullable<bool> _estado;
		
		private int _Id_cliente;
		
		private int _id_cajero;
		
		private EntitySet<detalle_pago_transaccion> _detalle_pago_transaccion;
		
		private EntitySet<detalle_transaccion> _detalle_transaccion;
		
		private EntityRef<Cajero> _Cajero;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_transaccionChanging(int value);
    partial void Onid_transaccionChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    partial void OnId_clienteChanging(int value);
    partial void OnId_clienteChanged();
    partial void Onid_cajeroChanging(int value);
    partial void Onid_cajeroChanged();
    #endregion
		
		public Transaccion()
		{
			this._detalle_pago_transaccion = new EntitySet<detalle_pago_transaccion>(new Action<detalle_pago_transaccion>(this.attach_detalle_pago_transaccion), new Action<detalle_pago_transaccion>(this.detach_detalle_pago_transaccion));
			this._detalle_transaccion = new EntitySet<detalle_transaccion>(new Action<detalle_transaccion>(this.attach_detalle_transaccion), new Action<detalle_transaccion>(this.detach_detalle_transaccion));
			this._Cajero = default(EntityRef<Cajero>);
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_transaccion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_transaccion
		{
			get
			{
				return this._id_transaccion;
			}
			set
			{
				if ((this._id_transaccion != value))
				{
					this.Onid_transaccionChanging(value);
					this.SendPropertyChanging();
					this._id_transaccion = value;
					this.SendPropertyChanged("id_transaccion");
					this.Onid_transaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Money")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cliente", DbType="Int NOT NULL")]
		public int Id_cliente
		{
			get
			{
				return this._Id_cliente;
			}
			set
			{
				if ((this._Id_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_clienteChanging(value);
					this.SendPropertyChanging();
					this._Id_cliente = value;
					this.SendPropertyChanged("Id_cliente");
					this.OnId_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cajero", DbType="Int NOT NULL")]
		public int id_cajero
		{
			get
			{
				return this._id_cajero;
			}
			set
			{
				if ((this._id_cajero != value))
				{
					if (this._Cajero.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_cajeroChanging(value);
					this.SendPropertyChanging();
					this._id_cajero = value;
					this.SendPropertyChanged("id_cajero");
					this.Onid_cajeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaccion_detalle_pago_transaccion", Storage="_detalle_pago_transaccion", ThisKey="id_transaccion", OtherKey="id_transaccion")]
		public EntitySet<detalle_pago_transaccion> detalle_pago_transaccion
		{
			get
			{
				return this._detalle_pago_transaccion;
			}
			set
			{
				this._detalle_pago_transaccion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaccion_detalle_transaccion", Storage="_detalle_transaccion", ThisKey="id_transaccion", OtherKey="id_transaccion")]
		public EntitySet<detalle_transaccion> detalle_transaccion
		{
			get
			{
				return this._detalle_transaccion;
			}
			set
			{
				this._detalle_transaccion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cajero_Transaccion", Storage="_Cajero", ThisKey="id_cajero", OtherKey="id_cajero", IsForeignKey=true)]
		public Cajero Cajero
		{
			get
			{
				return this._Cajero.Entity;
			}
			set
			{
				Cajero previousValue = this._Cajero.Entity;
				if (((previousValue != value) 
							|| (this._Cajero.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cajero.Entity = null;
						previousValue.Transaccion.Remove(this);
					}
					this._Cajero.Entity = value;
					if ((value != null))
					{
						value.Transaccion.Add(this);
						this._id_cajero = value.id_cajero;
					}
					else
					{
						this._id_cajero = default(int);
					}
					this.SendPropertyChanged("Cajero");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Transaccion", Storage="_Cliente", ThisKey="Id_cliente", OtherKey="Id_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Transaccion.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Transaccion.Add(this);
						this._Id_cliente = value.Id_cliente;
					}
					else
					{
						this._Id_cliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_pago_transaccion(detalle_pago_transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Transaccion = this;
		}
		
		private void detach_detalle_pago_transaccion(detalle_pago_transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Transaccion = null;
		}
		
		private void attach_detalle_transaccion(detalle_transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Transaccion = this;
		}
		
		private void detach_detalle_transaccion(detalle_transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Transaccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ventas")]
	public partial class Ventas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ventas;
		
		private string _codigo;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<decimal> _total;
		
		private string _Nit;
		
		private System.Nullable<bool> _estado;
		
		private int _Id_cliente;
		
		private EntitySet<Detalle_Ventas> _Detalle_Ventas;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ventasChanging(int value);
    partial void Onid_ventasChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void OnNitChanging(string value);
    partial void OnNitChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    partial void OnId_clienteChanging(int value);
    partial void OnId_clienteChanged();
    #endregion
		
		public Ventas()
		{
			this._Detalle_Ventas = new EntitySet<Detalle_Ventas>(new Action<Detalle_Ventas>(this.attach_Detalle_Ventas), new Action<Detalle_Ventas>(this.detach_Detalle_Ventas));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ventas", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_ventas
		{
			get
			{
				return this._id_ventas;
			}
			set
			{
				if ((this._id_ventas != value))
				{
					this.Onid_ventasChanging(value);
					this.SendPropertyChanging();
					this._id_ventas = value;
					this.SendPropertyChanged("id_ventas");
					this.Onid_ventasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="NVarChar(100)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Money")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nit", DbType="NVarChar(100)")]
		public string Nit
		{
			get
			{
				return this._Nit;
			}
			set
			{
				if ((this._Nit != value))
				{
					this.OnNitChanging(value);
					this.SendPropertyChanging();
					this._Nit = value;
					this.SendPropertyChanged("Nit");
					this.OnNitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cliente", DbType="Int NOT NULL")]
		public int Id_cliente
		{
			get
			{
				return this._Id_cliente;
			}
			set
			{
				if ((this._Id_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_clienteChanging(value);
					this.SendPropertyChanging();
					this._Id_cliente = value;
					this.SendPropertyChanged("Id_cliente");
					this.OnId_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ventas_Detalle_Ventas", Storage="_Detalle_Ventas", ThisKey="id_ventas", OtherKey="id_ventas")]
		public EntitySet<Detalle_Ventas> Detalle_Ventas
		{
			get
			{
				return this._Detalle_Ventas;
			}
			set
			{
				this._Detalle_Ventas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Ventas", Storage="_Cliente", ThisKey="Id_cliente", OtherKey="Id_cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Ventas.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Ventas.Add(this);
						this._Id_cliente = value.Id_cliente;
					}
					else
					{
						this._Id_cliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Ventas(Detalle_Ventas entity)
		{
			this.SendPropertyChanging();
			entity.Ventas = this;
		}
		
		private void detach_Detalle_Ventas(Detalle_Ventas entity)
		{
			this.SendPropertyChanging();
			entity.Ventas = null;
		}
	}
}
#pragma warning restore 1591
