#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace conexion_Linq_1.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Vehiculos")]
	public partial class MyDataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAño(Año instance);
    partial void UpdateAño(Año instance);
    partial void DeleteAño(Año instance);
    partial void InsertCondicion(Condicion instance);
    partial void UpdateCondicion(Condicion instance);
    partial void DeleteCondicion(Condicion instance);
    partial void InsertDueño(Dueño instance);
    partial void UpdateDueño(Dueño instance);
    partial void DeleteDueño(Dueño instance);
    partial void InsertGenero(Genero instance);
    partial void UpdateGenero(Genero instance);
    partial void DeleteGenero(Genero instance);
    partial void InsertMarca(Marca instance);
    partial void UpdateMarca(Marca instance);
    partial void DeleteMarca(Marca instance);
    partial void InsertModelo(Modelo instance);
    partial void UpdateModelo(Modelo instance);
    partial void DeleteModelo(Modelo instance);
    partial void InsertVehiculo(Vehiculo instance);
    partial void UpdateVehiculo(Vehiculo instance);
    partial void DeleteVehiculo(Vehiculo instance);
    #endregion
		
		public MyDataBaseDataContext() : 
				base(global::conexion_Linq_1.Properties.Settings.Default.VehiculosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyDataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Año> Año
		{
			get
			{
				return this.GetTable<Año>();
			}
		}
		
		public System.Data.Linq.Table<Condicion> Condicion
		{
			get
			{
				return this.GetTable<Condicion>();
			}
		}
		
		public System.Data.Linq.Table<Dueño> Dueño
		{
			get
			{
				return this.GetTable<Dueño>();
			}
		}
		
		public System.Data.Linq.Table<Genero> Genero
		{
			get
			{
				return this.GetTable<Genero>();
			}
		}
		
		public System.Data.Linq.Table<Marca> Marca
		{
			get
			{
				return this.GetTable<Marca>();
			}
		}
		
		public System.Data.Linq.Table<Modelo> Modelo
		{
			get
			{
				return this.GetTable<Modelo>();
			}
		}
		
		public System.Data.Linq.Table<Vehiculo> Vehiculo
		{
			get
			{
				return this.GetTable<Vehiculo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Año")]
	public partial class Año : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_año;
		
		private string _descripcion;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<Vehiculo> _Vehiculo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_añoChanging(int value);
    partial void Onid_añoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public Año()
		{
			this._Vehiculo = new EntitySet<Vehiculo>(new Action<Vehiculo>(this.attach_Vehiculo), new Action<Vehiculo>(this.detach_Vehiculo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_año", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_año
		{
			get
			{
				return this._id_año;
			}
			set
			{
				if ((this._id_año != value))
				{
					this.Onid_añoChanging(value);
					this.SendPropertyChanging();
					this._id_año = value;
					this.SendPropertyChanged("id_año");
					this.Onid_añoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(100)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Año_Vehiculo", Storage="_Vehiculo", ThisKey="id_año", OtherKey="id_año")]
		public EntitySet<Vehiculo> Vehiculo
		{
			get
			{
				return this._Vehiculo;
			}
			set
			{
				this._Vehiculo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vehiculo(Vehiculo entity)
		{
			this.SendPropertyChanging();
			entity.Año = this;
		}
		
		private void detach_Vehiculo(Vehiculo entity)
		{
			this.SendPropertyChanging();
			entity.Año = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Condicion")]
	public partial class Condicion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_condicion;
		
		private string _nombre;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<Vehiculo> _Vehiculo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_condicionChanging(int value);
    partial void Onid_condicionChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public Condicion()
		{
			this._Vehiculo = new EntitySet<Vehiculo>(new Action<Vehiculo>(this.attach_Vehiculo), new Action<Vehiculo>(this.detach_Vehiculo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_condicion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_condicion
		{
			get
			{
				return this._id_condicion;
			}
			set
			{
				if ((this._id_condicion != value))
				{
					this.Onid_condicionChanging(value);
					this.SendPropertyChanging();
					this._id_condicion = value;
					this.SendPropertyChanged("id_condicion");
					this.Onid_condicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Condicion_Vehiculo", Storage="_Vehiculo", ThisKey="id_condicion", OtherKey="id_condicion")]
		public EntitySet<Vehiculo> Vehiculo
		{
			get
			{
				return this._Vehiculo;
			}
			set
			{
				this._Vehiculo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vehiculo(Vehiculo entity)
		{
			this.SendPropertyChanging();
			entity.Condicion = this;
		}
		
		private void detach_Vehiculo(Vehiculo entity)
		{
			this.SendPropertyChanging();
			entity.Condicion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dueño")]
	public partial class Dueño : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_dueño;
		
		private int _id_genero;
		
		private string _nombre1;
		
		private string _nombre2;
		
		private string _apellido1;
		
		private string _apellido2;
		
		private string _apellidoCasad;
		
		private string _telefono;
		
		private string _dpi;
		
		private string _direccion;
		
		private string _nit;
		
		private string _correo;
		
		private bool _estado;
		
		private EntitySet<Vehiculo> _Vehiculo;
		
		private EntityRef<Genero> _Genero;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dueñoChanging(int value);
    partial void Onid_dueñoChanged();
    partial void Onid_generoChanging(int value);
    partial void Onid_generoChanged();
    partial void Onnombre1Changing(string value);
    partial void Onnombre1Changed();
    partial void Onnombre2Changing(string value);
    partial void Onnombre2Changed();
    partial void Onapellido1Changing(string value);
    partial void Onapellido1Changed();
    partial void Onapellido2Changing(string value);
    partial void Onapellido2Changed();
    partial void OnapellidoCasadChanging(string value);
    partial void OnapellidoCasadChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OndpiChanging(string value);
    partial void OndpiChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnnitChanging(string value);
    partial void OnnitChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    #endregion
		
		public Dueño()
		{
			this._Vehiculo = new EntitySet<Vehiculo>(new Action<Vehiculo>(this.attach_Vehiculo), new Action<Vehiculo>(this.detach_Vehiculo));
			this._Genero = default(EntityRef<Genero>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dueño", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_dueño
		{
			get
			{
				return this._id_dueño;
			}
			set
			{
				if ((this._id_dueño != value))
				{
					this.Onid_dueñoChanging(value);
					this.SendPropertyChanging();
					this._id_dueño = value;
					this.SendPropertyChanged("id_dueño");
					this.Onid_dueñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_genero", DbType="Int NOT NULL")]
		public int id_genero
		{
			get
			{
				return this._id_genero;
			}
			set
			{
				if ((this._id_genero != value))
				{
					if (this._Genero.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_generoChanging(value);
					this.SendPropertyChanging();
					this._id_genero = value;
					this.SendPropertyChanged("id_genero");
					this.Onid_generoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre1", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre1
		{
			get
			{
				return this._nombre1;
			}
			set
			{
				if ((this._nombre1 != value))
				{
					this.Onnombre1Changing(value);
					this.SendPropertyChanging();
					this._nombre1 = value;
					this.SendPropertyChanged("nombre1");
					this.Onnombre1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre2", DbType="NVarChar(100)")]
		public string nombre2
		{
			get
			{
				return this._nombre2;
			}
			set
			{
				if ((this._nombre2 != value))
				{
					this.Onnombre2Changing(value);
					this.SendPropertyChanging();
					this._nombre2 = value;
					this.SendPropertyChanged("nombre2");
					this.Onnombre2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido1", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string apellido1
		{
			get
			{
				return this._apellido1;
			}
			set
			{
				if ((this._apellido1 != value))
				{
					this.Onapellido1Changing(value);
					this.SendPropertyChanging();
					this._apellido1 = value;
					this.SendPropertyChanged("apellido1");
					this.Onapellido1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido2", DbType="NVarChar(100)")]
		public string apellido2
		{
			get
			{
				return this._apellido2;
			}
			set
			{
				if ((this._apellido2 != value))
				{
					this.Onapellido2Changing(value);
					this.SendPropertyChanging();
					this._apellido2 = value;
					this.SendPropertyChanged("apellido2");
					this.Onapellido2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidoCasad", DbType="NVarChar(100)")]
		public string apellidoCasad
		{
			get
			{
				return this._apellidoCasad;
			}
			set
			{
				if ((this._apellidoCasad != value))
				{
					this.OnapellidoCasadChanging(value);
					this.SendPropertyChanging();
					this._apellidoCasad = value;
					this.SendPropertyChanged("apellidoCasad");
					this.OnapellidoCasadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="NVarChar(100)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpi", DbType="NVarChar(100)")]
		public string dpi
		{
			get
			{
				return this._dpi;
			}
			set
			{
				if ((this._dpi != value))
				{
					this.OndpiChanging(value);
					this.SendPropertyChanging();
					this._dpi = value;
					this.SendPropertyChanged("dpi");
					this.OndpiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(300)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nit", DbType="NVarChar(15)")]
		public string nit
		{
			get
			{
				return this._nit;
			}
			set
			{
				if ((this._nit != value))
				{
					this.OnnitChanging(value);
					this.SendPropertyChanging();
					this._nit = value;
					this.SendPropertyChanged("nit");
					this.OnnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(100)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dueño_Vehiculo", Storage="_Vehiculo", ThisKey="id_dueño", OtherKey="id_dueño")]
		public EntitySet<Vehiculo> Vehiculo
		{
			get
			{
				return this._Vehiculo;
			}
			set
			{
				this._Vehiculo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Genero_Dueño", Storage="_Genero", ThisKey="id_genero", OtherKey="id_genero", IsForeignKey=true)]
		public Genero Genero
		{
			get
			{
				return this._Genero.Entity;
			}
			set
			{
				Genero previousValue = this._Genero.Entity;
				if (((previousValue != value) 
							|| (this._Genero.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Genero.Entity = null;
						previousValue.Dueño.Remove(this);
					}
					this._Genero.Entity = value;
					if ((value != null))
					{
						value.Dueño.Add(this);
						this._id_genero = value.id_genero;
					}
					else
					{
						this._id_genero = default(int);
					}
					this.SendPropertyChanged("Genero");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vehiculo(Vehiculo entity)
		{
			this.SendPropertyChanging();
			entity.Dueño = this;
		}
		
		private void detach_Vehiculo(Vehiculo entity)
		{
			this.SendPropertyChanging();
			entity.Dueño = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Genero")]
	public partial class Genero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_genero;
		
		private string _nombre;
		
		private bool _estado;
		
		private EntitySet<Dueño> _Dueño;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_generoChanging(int value);
    partial void Onid_generoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    #endregion
		
		public Genero()
		{
			this._Dueño = new EntitySet<Dueño>(new Action<Dueño>(this.attach_Dueño), new Action<Dueño>(this.detach_Dueño));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_genero", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_genero
		{
			get
			{
				return this._id_genero;
			}
			set
			{
				if ((this._id_genero != value))
				{
					this.Onid_generoChanging(value);
					this.SendPropertyChanging();
					this._id_genero = value;
					this.SendPropertyChanged("id_genero");
					this.Onid_generoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Genero_Dueño", Storage="_Dueño", ThisKey="id_genero", OtherKey="id_genero")]
		public EntitySet<Dueño> Dueño
		{
			get
			{
				return this._Dueño;
			}
			set
			{
				this._Dueño.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dueño(Dueño entity)
		{
			this.SendPropertyChanging();
			entity.Genero = this;
		}
		
		private void detach_Dueño(Dueño entity)
		{
			this.SendPropertyChanging();
			entity.Genero = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Marca")]
	public partial class Marca : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_marca;
		
		private string _nombre;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<Modelo> _Modelo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_marcaChanging(int value);
    partial void Onid_marcaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public Marca()
		{
			this._Modelo = new EntitySet<Modelo>(new Action<Modelo>(this.attach_Modelo), new Action<Modelo>(this.detach_Modelo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_marca", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_marca
		{
			get
			{
				return this._id_marca;
			}
			set
			{
				if ((this._id_marca != value))
				{
					this.Onid_marcaChanging(value);
					this.SendPropertyChanging();
					this._id_marca = value;
					this.SendPropertyChanged("id_marca");
					this.Onid_marcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Modelo", Storage="_Modelo", ThisKey="id_marca", OtherKey="id_marca")]
		public EntitySet<Modelo> Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				this._Modelo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Modelo(Modelo entity)
		{
			this.SendPropertyChanging();
			entity.Marca = this;
		}
		
		private void detach_Modelo(Modelo entity)
		{
			this.SendPropertyChanging();
			entity.Marca = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Modelo")]
	public partial class Modelo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_modelo;
		
		private int _id_marca;
		
		private string _nombre;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<Vehiculo> _Vehiculo;
		
		private EntityRef<Marca> _Marca;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_modeloChanging(int value);
    partial void Onid_modeloChanged();
    partial void Onid_marcaChanging(int value);
    partial void Onid_marcaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public Modelo()
		{
			this._Vehiculo = new EntitySet<Vehiculo>(new Action<Vehiculo>(this.attach_Vehiculo), new Action<Vehiculo>(this.detach_Vehiculo));
			this._Marca = default(EntityRef<Marca>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_modelo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_modelo
		{
			get
			{
				return this._id_modelo;
			}
			set
			{
				if ((this._id_modelo != value))
				{
					this.Onid_modeloChanging(value);
					this.SendPropertyChanging();
					this._id_modelo = value;
					this.SendPropertyChanged("id_modelo");
					this.Onid_modeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_marca", DbType="Int NOT NULL")]
		public int id_marca
		{
			get
			{
				return this._id_marca;
			}
			set
			{
				if ((this._id_marca != value))
				{
					if (this._Marca.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_marcaChanging(value);
					this.SendPropertyChanging();
					this._id_marca = value;
					this.SendPropertyChanged("id_marca");
					this.Onid_marcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modelo_Vehiculo", Storage="_Vehiculo", ThisKey="id_modelo", OtherKey="id_modelo")]
		public EntitySet<Vehiculo> Vehiculo
		{
			get
			{
				return this._Vehiculo;
			}
			set
			{
				this._Vehiculo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Marca_Modelo", Storage="_Marca", ThisKey="id_marca", OtherKey="id_marca", IsForeignKey=true)]
		public Marca Marca
		{
			get
			{
				return this._Marca.Entity;
			}
			set
			{
				Marca previousValue = this._Marca.Entity;
				if (((previousValue != value) 
							|| (this._Marca.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Marca.Entity = null;
						previousValue.Modelo.Remove(this);
					}
					this._Marca.Entity = value;
					if ((value != null))
					{
						value.Modelo.Add(this);
						this._id_marca = value.id_marca;
					}
					else
					{
						this._id_marca = default(int);
					}
					this.SendPropertyChanged("Marca");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vehiculo(Vehiculo entity)
		{
			this.SendPropertyChanging();
			entity.Modelo = this;
		}
		
		private void detach_Vehiculo(Vehiculo entity)
		{
			this.SendPropertyChanging();
			entity.Modelo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vehiculo")]
	public partial class Vehiculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_vehiculo;
		
		private int _id_dueño;
		
		private int _id_año;
		
		private int _id_condicion;
		
		private int _id_modelo;
		
		private bool _estado;
		
		private EntityRef<Año> _Año;
		
		private EntityRef<Condicion> _Condicion;
		
		private EntityRef<Dueño> _Dueño;
		
		private EntityRef<Modelo> _Modelo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vehiculoChanging(string value);
    partial void Onid_vehiculoChanged();
    partial void Onid_dueñoChanging(int value);
    partial void Onid_dueñoChanged();
    partial void Onid_añoChanging(int value);
    partial void Onid_añoChanged();
    partial void Onid_condicionChanging(int value);
    partial void Onid_condicionChanged();
    partial void Onid_modeloChanging(int value);
    partial void Onid_modeloChanged();
    partial void OnestadoChanging(bool value);
    partial void OnestadoChanged();
    #endregion
		
		public Vehiculo()
		{
			this._Año = default(EntityRef<Año>);
			this._Condicion = default(EntityRef<Condicion>);
			this._Dueño = default(EntityRef<Dueño>);
			this._Modelo = default(EntityRef<Modelo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vehiculo", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_vehiculo
		{
			get
			{
				return this._id_vehiculo;
			}
			set
			{
				if ((this._id_vehiculo != value))
				{
					this.Onid_vehiculoChanging(value);
					this.SendPropertyChanging();
					this._id_vehiculo = value;
					this.SendPropertyChanged("id_vehiculo");
					this.Onid_vehiculoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dueño", DbType="Int NOT NULL")]
		public int id_dueño
		{
			get
			{
				return this._id_dueño;
			}
			set
			{
				if ((this._id_dueño != value))
				{
					if (this._Dueño.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_dueñoChanging(value);
					this.SendPropertyChanging();
					this._id_dueño = value;
					this.SendPropertyChanged("id_dueño");
					this.Onid_dueñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_año", DbType="Int NOT NULL")]
		public int id_año
		{
			get
			{
				return this._id_año;
			}
			set
			{
				if ((this._id_año != value))
				{
					if (this._Año.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_añoChanging(value);
					this.SendPropertyChanging();
					this._id_año = value;
					this.SendPropertyChanged("id_año");
					this.Onid_añoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_condicion", DbType="Int NOT NULL")]
		public int id_condicion
		{
			get
			{
				return this._id_condicion;
			}
			set
			{
				if ((this._id_condicion != value))
				{
					if (this._Condicion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_condicionChanging(value);
					this.SendPropertyChanging();
					this._id_condicion = value;
					this.SendPropertyChanged("id_condicion");
					this.Onid_condicionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_modelo", DbType="Int NOT NULL")]
		public int id_modelo
		{
			get
			{
				return this._id_modelo;
			}
			set
			{
				if ((this._id_modelo != value))
				{
					if (this._Modelo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_modeloChanging(value);
					this.SendPropertyChanging();
					this._id_modelo = value;
					this.SendPropertyChanged("id_modelo");
					this.Onid_modeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit NOT NULL")]
		public bool estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Año_Vehiculo", Storage="_Año", ThisKey="id_año", OtherKey="id_año", IsForeignKey=true)]
		public Año Año
		{
			get
			{
				return this._Año.Entity;
			}
			set
			{
				Año previousValue = this._Año.Entity;
				if (((previousValue != value) 
							|| (this._Año.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Año.Entity = null;
						previousValue.Vehiculo.Remove(this);
					}
					this._Año.Entity = value;
					if ((value != null))
					{
						value.Vehiculo.Add(this);
						this._id_año = value.id_año;
					}
					else
					{
						this._id_año = default(int);
					}
					this.SendPropertyChanged("Año");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Condicion_Vehiculo", Storage="_Condicion", ThisKey="id_condicion", OtherKey="id_condicion", IsForeignKey=true)]
		public Condicion Condicion
		{
			get
			{
				return this._Condicion.Entity;
			}
			set
			{
				Condicion previousValue = this._Condicion.Entity;
				if (((previousValue != value) 
							|| (this._Condicion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Condicion.Entity = null;
						previousValue.Vehiculo.Remove(this);
					}
					this._Condicion.Entity = value;
					if ((value != null))
					{
						value.Vehiculo.Add(this);
						this._id_condicion = value.id_condicion;
					}
					else
					{
						this._id_condicion = default(int);
					}
					this.SendPropertyChanged("Condicion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dueño_Vehiculo", Storage="_Dueño", ThisKey="id_dueño", OtherKey="id_dueño", IsForeignKey=true)]
		public Dueño Dueño
		{
			get
			{
				return this._Dueño.Entity;
			}
			set
			{
				Dueño previousValue = this._Dueño.Entity;
				if (((previousValue != value) 
							|| (this._Dueño.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dueño.Entity = null;
						previousValue.Vehiculo.Remove(this);
					}
					this._Dueño.Entity = value;
					if ((value != null))
					{
						value.Vehiculo.Add(this);
						this._id_dueño = value.id_dueño;
					}
					else
					{
						this._id_dueño = default(int);
					}
					this.SendPropertyChanged("Dueño");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Modelo_Vehiculo", Storage="_Modelo", ThisKey="id_modelo", OtherKey="id_modelo", IsForeignKey=true)]
		public Modelo Modelo
		{
			get
			{
				return this._Modelo.Entity;
			}
			set
			{
				Modelo previousValue = this._Modelo.Entity;
				if (((previousValue != value) 
							|| (this._Modelo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Modelo.Entity = null;
						previousValue.Vehiculo.Remove(this);
					}
					this._Modelo.Entity = value;
					if ((value != null))
					{
						value.Vehiculo.Add(this);
						this._id_modelo = value.id_modelo;
					}
					else
					{
						this._id_modelo = default(int);
					}
					this.SendPropertyChanged("Modelo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
